### ISSUE TITLE
Обрезается тень у элементов LessonInfoFragment

### ISSUE THREAD

**Issue by tonykolomeytsev** [mospolyhelper/mospolyhelper-android#92]
На экране `LessonInfoFragment `обрезается тень у `Chip`'ов:

![ui_issue](https://user-images.githubusercontent.com/18632470/108839284-ee3f0480-75e5-11eb-84f7-ee3f33e3a384.png)

**Comment by tipapro** [comment]
Я уже начал переделывать расписание и связанное с ним, поэтому не вижу смысла фиксить. Фрагмент информации о паре будет выглядеть как в приложухе Google I/O (для групп, преподов и аудиторий)
![Screenshot_2021-02-23-15-01-12-239_com_google_samples_apps_iosched](https://user-images.githubusercontent.com/17129060/108841019-2cd5be80-75e8-11eb-8012-e0b44f7b2a9e.jpg)
