### ISSUE TITLE
The 'kotlin-android-extensions' Gradle plugin is deprecated

### ISSUE THREAD

**Issue by tonykolomeytsev** [mospolyhelper/mospolyhelper-android#94]
У вас в проекте используются котлиновские синтетики (причем есть фрагменты где до сих пор используется `findViewById`). `kotlin-android-extensions` плагин больше не будет поддерживаться командой JetBrains. Нужно мигрировать приложение не viewBinding.
Если вы юзаете `Parcelize`, то можно подключить только `kotlin-parcelize` плагин.

Если интересно, могу предложить своё решение и завести пулл-реквест с миграцией на ViewBinding.
Решение буду брать отсюда: https://habr.com/ru/post/501158/ 

Если объяснять в двух словах, то после миграции во фрагментах вам надо будет объявлять поле:
```kotlin
// MyFragmentBinding генерируется автоматически, как класс R
val binding by viewBinding(MyFragmentBinding::bind)
```

И внутри объекта binding будут доступны все вьюхи по их `id`. Кучу boilerplate кода с findViewById можно будет больше не писать.

**Comment by tipapro** [comment]
Мы думали об этом, но решили подождать, пока выйдет поддержка StateFlow для биндинга (в стабильной версии), (и пока доделаем кучу другой работы по переделке расписания и переноса личного кабинета)
https://developer.android.com/topic/libraries/data-binding/observability#stateflow

**Comment by tonykolomeytsev** [comment]
Понял! Значит нужно ждать релиза Android Gradle Plugin версии 7.0
В принципе, в реалиях использования LiveData и других Jetpack плюшек, StateFlow органичнее будет смотреться в этом проекте.
Тогда пусть висит Issue, напоминает о том, что когда-то придется совершить миграцию.

**Comment by tipapro** [comment]
kotlin-android-extensions выпилен из проекта. В 99% мест используется viewBinding
